# Generated by Django 4.2.4 on 2023-08-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('paal_score', models.IntegerField(default=0)),
                ('piel_score', models.IntegerField(default=0)),
                ('hitpael_score', models.IntegerField(default=0)),
                ('hifil_score', models.IntegerField(default=0)),
                ('nifal_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='verbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=30)),
                ('hebrew_word', models.CharField(max_length=30)),
                ('root', models.CharField(max_length=30)),
                ('part_of_speech', models.CharField(max_length=30)),
                ('meaning', models.TextField(verbose_name='')),
                ('niqqud_stripped_word', models.CharField(max_length=30)),
            ],
        ),
    ]
